export function pad2(value: number): string {
	return value.toString().padStart(2, '0')
}

export function pad3(value: number): string {
	return value.toString().padStart(3, '0')
}

// Format duration in milliseconds to HH:MM:SS.mmm or HH:MM:SS
export function formatDuration(ms: number, withMillis: boolean = true): string {
	const totalSeconds = Math.max(0, Math.floor(ms / 1000))
	const hours = Math.floor(totalSeconds / 3600)
	const minutes = Math.floor((totalSeconds % 3600) / 60)
	const seconds = totalSeconds % 60
	const millis = Math.max(0, ms % 1000)
	const base = `${pad2(hours)}:${pad2(minutes)}:${pad2(seconds)}`
	return withMillis ? `${base}.${pad3(millis)}` : base
}

export function clampNumber(value: number, min: number, max: number): number {
	return Math.min(max, Math.max(min, value))
}

// Hebrew translations for common timezone areas
const HEBREW_TIMEZONE_TRANSLATIONS: Record<string, string> = {
	// Continents
	'Africa': 'אפריקה',
	'America': 'אמריקה',
	'Asia': 'אסיה',
	'Australia': 'אוסטרליה',
	'Europe': 'אירופה',
	'Pacific': 'פסיפיק',
	'Atlantic': 'אטלנטיק',
	'Indian': 'הודו',
	'Arctic': 'ארקטי',
	'Antarctica': 'אנטארקטיקה',
	'Eastern': 'מזרח',
	'Western': 'מערב',
	'Central': 'מרכז',
	'Mountain': 'הרים',
	'Northern': 'צפון',
	'Southern': 'דרום',
	'Indiana': 'אינדיאנה',
	'North Dakota': 'צפון דקוטה',
	'South Dakota': 'דרום דקוטה',
	'Kentucky': 'קנטקי',
	'Tennessee': 'טנסי',
	'Indianapolis': 'אינדיאנפוליס',
	'Knox': 'נוקס',
	'Marengo': 'מרנגו',
	'Petersburg': 'פטרסבורג',
	'Tell City': 'טל סיטי',
	'Vevay': 'וויי',
	'Vincennes': 'וינסנס',
	'Winamac': 'ווינמאק',
	'Center': 'מרכז',
	'New Salem': 'ניו סלם',
	'Beulah': 'בולה',
	'Menominee': 'מנומיני',
	'Metlakatla': 'מטלקטלה',
	'Sitka': 'סיטקה',
	'Juneau': 'ג\'ונו',
	'Yakutat': 'יקטוט',
	'Nome': 'נום',
	'Adak': 'אדאק',
	'Hawaii': 'הוואי',
	
	// Major cities - Africa
	'Cairo': 'קהיר',
	'Johannesburg': 'יוהנסבורג',
	'Lagos': 'לאגוס',
	'Casablanca': 'קזבלנקה',
	'Accra': 'אקרה',
	'Nairobi': 'ניירובי',
	'Addis Ababa': 'אדיס אבבה',
	'Algiers': 'אלג\'יר',
	'Tunis': 'תוניס',
	'Kinshasa': 'קינשאסה',
	'Lubumbashi': 'לובומבאשי',
	'Maputo': 'מפוטו',
	'Luanda': 'לואנדה',
	'Dar es Salaam': 'דאר א-סלאם',
	'Kampala': 'קמפלה',
	'Khartoum': 'חרטום',
	'Juba': 'ג\'ובה',
	'Abidjan': 'אבידג\'ן',
	'Dakar': 'דקר',
	'Bamako': 'במאקו',
	'Conakry': 'קונאקרי',
	'Freetown': 'פריטאון',
	'Monrovia': 'מונרוביה',
	'Lome': 'לומה',
	'Porto-Novo': 'פורטו-נובו',
	'Yaounde': 'יאונדה',
	'Libreville': 'ליברוויל',
	'Brazzaville': 'ברזוויל',
	'Windhoek': 'וינדהוק',
	'Gaborone': 'גאבורון',
	'Harare': 'הארארה',
	'Lusaka': 'לוסקה',
	'Blantyre': 'בלנטייר',
	'Antananarivo': 'אנטננריבו',
	'Port Louis': 'פורט לואי',
	'Moroni': 'מורוני',
	'Victoria': 'ויקטוריה',
	'Mogadishu': 'מוגדישו',
	'Djibouti': 'ג\'יבוטי',
	'Asmara': 'אסמרה',
	'Cape Verde': 'כף ורדה',
	'Sao Tome': 'סאו טומה',
	
	// Major cities - America
	'New York': 'ניו יורק',
	'Chicago': 'שיקגו',
	'Los Angeles': 'לוס אנג\'לס',
	'Denver': 'דנבר',
	'Phoenix': 'פיניקס',
	'Anchorage': 'אנקורג',
	'Honolulu': 'הונולולו',
	'Toronto': 'טורונטו',
	'Montreal': 'מונטריאול',
	'Vancouver': 'ונקובר',
	'Winnipeg': 'וויניפג',
	'Edmonton': 'אדמונטון',
	'Calgary': 'קלגרי',
	'Halifax': 'הליפקס',
	'St Johns': 'סנט ג\'ונס',
	'Mexico City': 'מקסיקו סיטי',
	'Guadalajara': 'גואדלחרה',
	'Monterrey': 'מונטריי',
	'Tijuana': 'טיחואנה',
	'Merida': 'מרידה',
	'Cancun': 'קנקון',
	'Guatemala': 'גואטמלה',
	'Belize': 'בליז',
	'San Salvador': 'סן סלבדור',
	'Tegucigalpa': 'טגוסיגלפה',
	'Managua': 'מנגואה',
	'San Jose': 'סן חוזה',
	'Panama': 'פנמה',
	'Bogota': 'בוגוטה',
	'Lima': 'לימה',
	'Quito': 'קיטו',
	'Guayaquil': 'גויאקיל',
	'Caracas': 'קראקס',
	'Maracaibo': 'מרוקייבו',
	'Georgetown': 'ג\'ורג\'טאון',
	'Paramaribo': 'פרמריבו',
	'Cayenne': 'קיין',
	'Brasilia': 'ברזיליה',
	'Sao Paulo': 'סאו פאולו',
	'Rio de Janeiro': 'ריו דה ז\'ניירו',
	'Recife': 'רסיפה',
	'Fortaleza': 'פורטלזה',
	'Belem': 'בלם',
	'Manaus': 'מנאוס',
	'Buenos Aires': 'בואנוס איירס',
	'Cordoba': 'קורדובה',
	'Rosario': 'רוסריו',
	'Montevideo': 'מונטווידאו',
	'Asuncion': 'אסונסיון',
	'La Paz': 'לה פאז',
	'Sucre': 'סוקרה',
	'Santiago': 'סנטיאגו',
	'Valparaiso': 'ולפראיסו',
	
	// Major cities - Asia
	'Jerusalem': 'ירושלים',
	'Tel Aviv': 'תל אביב',
	'Beirut': 'ביירות',
	'Damascus': 'דמשק',
	'Amman': 'עמאן',
	'Baghdad': 'בגדד',
	'Basra': 'בצרה',
	'Riyadh': 'ריאד',
	'Jeddah': 'ג\'דה',
	'Mecca': 'מכה',
	'Medina': 'מדינה',
	'Kuwait': 'כווית',
	'Doha': 'דוחה',
	'Abu Dhabi': 'אבו דאבי',
	'Dubai': 'דובאי',
	'Sharjah': 'שארג\'ה',
	'Muscat': 'מסקט',
	'Sanaa': 'צנעא',
	'Aden': 'עדן',
	'Tehran': 'טהרן',
	'Isfahan': 'איספהאן',
	'Mashhad': 'משהד',
	'Kabul': 'קאבול',
	'Islamabad': 'אסמבאד',
	'Karachi': 'קראצ\'י',
	'Lahore': 'לאהור',
	'Multan': 'מולטן',
	'New Delhi': 'ניו דלהי',
	'Mumbai': 'מומבאי',
	'Kolkata': 'קולקטה',
	'Chennai': 'צ\'נאי',
	'Bangalore': 'בנגלור',
	'Hyderabad': 'היידראבאד',
	'Pune': 'פונה',
	'Ahmedabad': 'אחמדאבאד',
	'Jaipur': 'ג\'איפור',
	'Surat': 'סוראט',
	'Lucknow': 'לקנאו',
	'Kanpur': 'קנפור',
	'Nagpur': 'נאגפור',
	'Indore': 'אינדור',
	'Thane': 'תאנה',
	'Bhopal': 'בופאל',
	'Visakhapatnam': 'ופטנאם',
	'Patna': 'פטנה',
	'Vadodara': 'ואדודרה',
	'Ghaziabad': 'גאזיאבאד',
	'Ludhiana': 'לודיאנה',
	'Agra': 'אגרה',
	'Nashik': 'נשיק',
	'Faridabad': 'פרידאבאד',
	'Meerut': 'מירוט',
	'Rajkot': 'ראג\'קוט',
	'Varanasi': 'וואראנסי',
	'Srinagar': 'סרינגאר',
	'Amritsar': 'אמריצר',
	'Dhaka': 'דאקה',
	'Chittagong': 'צ\'יטאגונג',
	'Rangoon': 'רנגון',
	'Yangon': 'יאנגון',
	'Bangkok': 'בנגקוק',
	'Chiang Mai': 'צ\'יאנג מאי',
	'Phnom Penh': 'פנום פן',
	'Vientiane': 'ויינטיאן',
	'Ho Chi Minh': 'הו צ\'י מין',
	'Hanoi': 'האנוי',
	'Jakarta': 'ג\'קרטה',
	'Surabaya': 'סוראבאיה',
	'Bandung': 'בנדונג',
	'Medan': 'מדאן',
	'Semarang': 'סמרונג',
	'Palembang': 'פלמבאנג',
	'Makassar': 'מקאסאר',
	'Kuala Lumpur': 'קואלה לומפור',
	'George Town': 'ג\'ורג\' טאון',
	'Johor Bahru': 'ג\'והור בארו',
	'Singapore': 'סינגפור',
	'Manila': 'מנילה',
	'Cebu': 'סאבו',
	'Davao': 'דאוואו',
	'Bandar Seri Begawan': 'בנדר סרי בגוואן',
	'Colombo': 'קולומבו',
	'Kandy': 'קנדי',
	'Male': 'מאלה',
	'Thimphu': 'תימפה',
	'Kathmandu': 'קטמנדו',
	'Ulaanbaatar': 'אולן בטור',
	'Pyongyang': 'פיונגיאנג',
	'Seoul': 'סיאול',
	'Busan': 'בוסאן',
	'Incheon': 'אינצ\'ון',
	'Daegu': 'דאיגו',
	'Daejeon': 'דאיג\'ון',
	'Gwangju': 'גוואנגג\'ו',
	'Ulsan': 'אולסן',
	'Tokyo': 'טוקיו',
	'Osaka': 'אוסקה',
	'Yokohama': 'יוקוהמה',
	'Nagoya': 'נגויה',
	'Sapporo': 'סאפורו',
	'Fukuoka': 'פוקואוקה',
	'Kobe': 'קובה',
	'Kyoto': 'קיוטו',
	'Sendai': 'סנדאי',
	'Hiroshima': 'הירושימה',
	'Kitakyushu': 'קיטאקיושו',
	'Beijing': 'בייג\'ינג',
	'Shanghai': 'שאנגחאי',
	'Guangzhou': 'גואנגז\'ו',
	'Shenzhen': 'שנז\'ן',
	'Chengdu': 'צ\'נגדו',
	'Chongqing': 'צ\'ונגצ\'ינג',
	'Wuhan': 'ווהאן',
	'Xi\'an': 'שיאן',
	'Hangzhou': 'האנגז\'ו',
	'Tianjin': 'טיינג\'ין',
	'Nanjing': 'נאנג\'ינג',
	'Qingdao': 'צ\'ינגדאו',
	'Dalian': 'דאליאן',
	'Zhengzhou': 'ז\'נגז\'ו',
	'Changsha': 'צ\'אנגשה',
	'Kunming': 'קונמינג',
	'Urumqi': 'אורומצ\'י',
	'Fuzhou': 'פוז\'ו',
	'Shijiazhuang': 'שיג\'יאז\'ואנג',
	'Xiamen': 'שיאמן',
	'Harbin': 'הרבין',
	'Taipei': 'טאיפי',
	'Kaohsiung': 'קאוהיונג',
	'Taichung': 'טאיצונג',
	'Tainan': 'טאינאן',
	'Hong Kong': 'הונג קונג',
	'Macau': 'מקאו',
	
	// Major cities - Australia
	'Sydney': 'סידני',
	'Melbourne': 'מלבורן',
	'Brisbane': 'בריסביין',
	'Perth': 'פרת',
	'Adelaide': 'אדלייד',
	'Gold Coast': 'גולד קואסט',
	'Newcastle': 'ניוקאסל',
	'Canberra': 'קנברה',
	'Sunshine Coast': 'סאנשיין קואסט',
	'Wollongong': 'וולונגונג',
	'Hobart': 'הובארט',
	'Geelong': 'ג\'ילונג',
	'Townsville': 'טאונסוויל',
	'Cairns': 'קיירנס',
	'Darwin': 'דארווין',
	'Toowoomba': 'טוובומבה',
	'Ballarat': 'בלאראט',
	'Bendigo': 'בנדיגו',
	'Albury': 'אלבורי',
	'Launceston': 'לונסטון',
	'Mackay': 'מקאי',
	'Rockhampton': 'רוקהמפטון',
	'Bunbury': 'בנבורי',
	'Bundaberg': 'בונדאברג',
	'Coffs Harbour': 'קופס הארבור',
	'Wagga Wagga': 'וואגה וואגה',
	'Hervey Bay': 'הרווי ביי',
	'Port Macquarie': 'פורט מקווארי',
	'Shepparton': 'שפרטון',
	'Melton': 'מלטון',
	'Dubbo': 'דובו',
	'Gladstone': 'גלאדסטון',
	'Mildura': 'מילדורה',
	'Lismore': 'ליסמור',
	'Warrnambool': 'ווארנאמבול',
	'Tamworth': 'טאמוורת',
	'Orange': 'אורנג\'',
	'Bathurst': 'באת\'ורסט',
	'Auckland': 'אוקלנד',
	'Wellington': 'ולינגטון',
	'Christchurch': 'כרייסטצ\'רץ\'',
	'Hamilton': 'המילטון',
	'Napier': 'נפייר',
	'Dunedin': 'דונדין',
	'Palmerston North': 'פלמרסטון נורת\'',
	'Nelson': 'נלסון',
	'Rotorua': 'רוטורואה',
	'New Plymouth': 'ניו פלימות',
	'Whangarei': 'וואנגארי',
	'Invercargill': 'אינברקארגיל',
	'Wanganui': 'וואנגאנואי',
	'Gisborne': 'גיסבורן',
	'Tauranga': 'טאוראנגה',
	'Lower Hutt': 'לואר האט',
	'Hastings': 'הסטינגס',
	'Timaru': 'טימארו',
	'Upper Hutt': 'אפר האט',
	'Whakatane': 'וואקאטנה',
	'Masterton': 'מאסטרטון',
	'Blenheim': 'בלנהיים',
	'Taupo': 'טאופו',
	'Pukekohe': 'פוקיקואה',
	'Rangiora': 'ראנגיורה',
	'Ashburton': 'אשברטון',
	'Levin': 'לווין',
	'Kapiti': 'קאפיטי',
	'Gore': 'גור',
	'Oamaru': 'אואמרו',
	
	// Major cities - Pacific
	'Pago Pago': 'פגו פגו',
	'Apia': 'אפיה',
	'Nuku\'alofa': 'נוקואלופה',
	'Fakaofo': 'פקאופו',
	'Chatham': 'צ\'אטהם',
	'Rarotonga': 'ררוטונגה',
	'Pitcairn': 'פיטקרן',
	'Easter': 'פסחא',
	'Galapagos': 'גלפגוס',
	'Marquesas': 'מרקיז',
	'Gambier': 'גמבייה',
	'Fiji': 'פיג\'י',
	'Port Moresby': 'פורט מורסבי',
	'Guam': 'גואם',
	'Saipan': 'סאיפן',
	'Palau': 'פאלאו',
	'Majuro': 'מג\'ורו',
	'Kwajalein': 'קווג\'לין',
	'Chuuk': 'צ\'וק',
	'Pohnpei': 'פוהנפיי',
	'Kosrae': 'קוסאי',
	'Yap': 'יאפ',
	'Tarawa': 'טראווה',
	'Enderbury': 'אנדרבורי',
	'Kiritimati': 'קיריטימטי',
	'Funafuti': 'פונאפוטי',
	'Midway': 'מידוויי',
	'Guadalcanal': 'גואדלקנל',
	'Norfolk': 'נורפוק',
	'Port Vila': 'פורט וילה',
	'Noumea': 'נומאה',
	
	// Major cities - Europe
	'London': 'לונדון',
	'Dublin': 'דבלין',
	'Belfast': 'בלפסט',
	'Edinburgh': 'אדינבורו',
	'Glasgow': 'גלאזגו',
	'Paris': 'פריז',
	'Lyon': 'ליון',
	'Marseille': 'מרסיי',
	'Nice': 'ניס',
	'Toulouse': 'טולוז',
	'Berlin': 'ברלין',
	'Munich': 'מינכן',
	'Frankfurt': 'פרנקפורט',
	'Hamburg': 'המבורג',
	'Cologne': 'קלן',
	'Stuttgart': 'שטוטגרט',
	'Dusseldorf': 'דיסלדורף',
	'Dortmund': 'דורטמונד',
	'Essen': 'אסן',
	'Leipzig': 'לייפציג',
	'Dresden': 'דרזדן',
	'Hannover': 'הנובר',
	'Nuremberg': 'נירנברג',
	'Rome': 'רומא',
	'Milan': 'מילאנו',
	'Naples': 'נאפולי',
	'Turin': 'טורין',
	'Palermo': 'פלרמו',
	'Genoa': 'גנואה',
	'Bologna': 'בולוניה',
	'Florence': 'פירנצה',
	'Venice': 'ונציה',
	'Madrid': 'מדריד',
	'Barcelona': 'ברצלונה',
	'Valencia': 'ולנסיה',
	'Seville': 'סביליה',
	'Zaragoza': 'סרגוסה',
	'Malaga': 'מלגה',
	'Murcia': 'מורסיה',
	'Palma': 'פלמה',
	'Las Palmas': 'לאס פאלמאס',
	'Bilbao': 'בילבאו',
	'Lisbon': 'ליסבון',
	'Porto': 'פורטו',
	'Amsterdam': 'אמסטרדם',
	'Rotterdam': 'רוטרדם',
	'The Hague': 'האג',
	'Utrecht': 'אוטרכט',
	'Eindhoven': 'איינדהובן',
	'Brussels': 'בריסל',
	'Antwerp': 'אנטוורפן',
	'Ghent': 'גנט',
	'Charleroi': 'שרלרואה',
	'Bruges': 'ברוז',
	'Vienna': 'וינה',
	'Graz': 'גראץ',
	'Linz': 'לינץ',
	'Salzburg': 'זלצבורג',
	'Innsbruck': 'אינסברוק',
	'Prague': 'פראג',
	'Brno': 'ברנו',
	'Ostrava': 'אוסטרבה',
	'Plzen': 'פלזן',
	'Budapest': 'בודפשט',
	'Debrecen': 'דברצן',
	'Szeged': 'סגד',
	'Miskolc': 'מישקולץ',
	'Pecs': 'פץ',
	'Warsaw': 'ורשה',
	'Krakow': 'קרקוב',
	'Lodz': 'לודז',
	'Wroclaw': 'ורוצלב',
	'Poznan': 'פוזנן',
	'Gdansk': 'גדנסק',
	'Stockholm': 'סטוקהולם',
	'Gothenburg': 'גוטבורג',
	'Malmö': 'מאלמה',
	'Uppsala': 'אופסלה',
	'Vasteras': 'וסטרס',
	'Oslo': 'אוסלו',
	'Bergen': 'ברגן',
	'Trondheim': 'טרונדהיים',
	'Stavanger': 'סטוונגר',
	'Bærum': 'ברום',
	'Helsinki': 'הלסינקי',
	'Espoo': 'אספו',
	'Tampere': 'טמפרה',
	'Vantaa': 'ונטה',
	'Oulu': 'אולו',
	'Copenhagen': 'קופנהגן',
	'Aarhus': 'ארהוס',
	'Odense': 'אודנסה',
	'Aalborg': 'אולבורג',
	'Esbjerg': 'אסביירג',
	'Moscow': 'מוסקבה',
	'Saint Petersburg': 'סנט פטרסבורג',
	'Novosibirsk': 'נובוסיבירסק',
	'Yekaterinburg': 'יקטרינבורג',
	'Nizhny Novgorod': 'ניז\'ני נובגורוד',
	'Kazan': 'קאזאן',
	'Chelyabinsk': 'צ\'ליאבינסק',
	'Omsk': 'אומסק',
	'Samara': 'סמארה',
	'Rostov-on-Don': 'רוסטוב על הדון',
	'Ufa': 'אופה',
	'Krasnoyarsk': 'קרסנויארסק',
	'Voronezh': 'וורונז\'',
	'Perm': 'פרם',
	'Volgograd': 'וולגוגרד',
	'Kiev': 'קייב',
	'Kharkiv': 'חרקוב',
	'Odessa': 'אודסה',
	'Dnipro': 'דניפרו',
	'Donetsk': 'דונצק',
	'Zaporizhzhia': 'זפוריז\'זיה',
	'Lviv': 'לביב',
	'Kryvyi Rih': 'קריבי ריה',
	'Mykolaiv': 'מיקולאייב',
	'Mariupol': 'מריופול',
	'Luhansk': 'לוהנסק',
	'Sevastopol': 'סבסטופול',
	'Simferopol': 'סימפרופול',
	'Bucharest': 'בוקרשט',
	'Cluj-Napoca': 'קלוז\'-נאפוקה',
	'Timisoara': 'טימישוארה',
	'Iasi': 'יאוסי',
	'Constanta': 'קונסטנצה',
	'Craiova': 'קראיובה',
	'Brasov': 'בראשוב',
	'Galati': 'גלאצי',
	'Ploiesti': 'פלוישטי',
	'Oradea': 'אורדיה',
	'Sofia': 'סופיה',
	'Plovdiv': 'פלובדיב',
	'Varna': 'וארנה',
	'Burgas': 'בורגאס',
	'Ruse': 'רוסה',
	'Stara Zagora': 'סטארה זאגורה',
	'Athens': 'אתונה',
	'Thessaloniki': 'תסלוניקי',
	'Patras': 'פטרס',
	'Heraklion': 'הרקליון',
	'Larissa': 'לריסה',
	'Volos': 'וולוס',
	'Rhodes': 'רודוס',
	'Ioannina': 'יואנינה',
	'Chania': 'צ\'אניה',
	'Istanbul': 'איסטנבול',
	'Ankara': 'אנקרה',
	'Izmir': 'איזמיר',
	'Bursa': 'בורסה',
	'Antalya': 'אנטליה',
	'Adana': 'אדנה',
	'Gaziantep': 'גזיאנטפ',
	'Konya': 'קוניה',
	'Cankaya': 'צ\'נקאיה',
	'Mersin': 'מרסין',
	'Diyarbakir': 'דיארבקיר',
	'Kayseri': 'קאיסרי',
	'Eskisehir': 'אסקישהיר',
	'Zagreb': 'זאגרב',
	'Split': 'ספליט',
	'Rijeka': 'רייקה',
	'Osijek': 'אוסייק',
	'Zadar': 'זאדאר',
	'Belgrade': 'בלגרד',
	'Novi Sad': 'נובי סאד',
	'Nis': 'ניש',
	'Kragujevac': 'קראגוייבץ',
	'Subotica': 'סובוטיצה',
	'Ljubljana': 'ליובליאנה',
	'Maribor': 'מריבור',
	'Celje': 'צליה',
	'Kranj': 'קראן',
	'Koper': 'קופר',
	'Sarajevo': 'סarajevo',
	'Banja Luka': 'בניה לוקה',
	'Tuzla': 'טוזלה',
	'Zenica': 'זניצה',
	'Mostar': 'מוסטאר',
	'Skopje': 'סקופיה',
	'Bitola': 'ביטולה',
	'Kumanovo': 'קומנובו',
	'Prilep': 'פרילפ',
	'Tetovo': 'טטובו',
	'Tirana': 'טירנה',
	'Durres': 'דורס',
	'Vlore': 'ולורה',
	'Shkoder': 'שקודר',
	'Fier': 'פייר',
	'Reykjavik': 'רייקיאוויק',
	'Kopavogur': 'קופאבוגור',
	'Hafnarfjordur': 'הפנארפירדור',
	'Akureyri': 'אקוריירי',
	'Riga': 'ריגה',
	'Daugavpils': 'דאוגבפילס',
	'Liepaja': 'ליפאיה',
	'Jelgava': 'ג\'לגבה',
	'Jurmala': 'יורמאלה',
	'Vilnius': 'וילנה',
	'Kaunas': 'קובנה',
	'Klaipeda': 'קליפדה',
	'Siauliai': 'שאוליאי',
	'Panevezys': 'פנבזיס',
	'Tallinn': 'טאלין',
	'Tartu': 'טרטו',
	'Narva': 'נרווה',
	'Parnu': 'פארנו',
	'Kohtla-Jarve': 'קוהלה-יארוה',
	'Valletta': 'ולטה',
	'Birkirkara': 'בירקירקארה',
	'Qormi': 'קורמי',
	'Mosta': 'מוסטה',
	'Rabat': 'רבאט',
	'Nicosia': 'ניקוסיה',
	'Limassol': 'לימסול',
	'Larnaca': 'לרנקה',
	'Paphos': 'פאפוס',
	'Famagusta': 'פמגוסטה',
	'Kyrenia': 'קירניה',
}

// Returns browser supported time zones
export function getSupportedTimeZones(): string[] {
	// Modern browsers support this
	// Fallback to common timezones if not supported
	// @ts-ignore
	if (Intl.supportedValuesOf) {
		// @ts-ignore
		return Intl.supportedValuesOf('timeZone') as string[]
	}
	return [
		'Africa/Cairo', 'Africa/Johannesburg',
		'America/Chicago', 'America/Los_Angeles', 'America/New_York', 'America/Sao_Paulo',
		'Asia/Dubai', 'Asia/Hong_Kong', 'Asia/Jerusalem', 'Asia/Kolkata', 'Asia/Singapore', 'Asia/Tokyo',
		'Australia/Sydney',
		'Europe/Amsterdam', 'Europe/Berlin', 'Europe/London', 'Europe/Madrid', 'Europe/Paris',
		'Pacific/Auckland'
	]
}

export function timeZoneToLabel(tz: string): string {
	const parts = tz.split('/')
	const city = parts[parts.length - 1].replace(/_/g, ' ')
	return city
}

// Convert timezone to Hebrew
export function timeZoneToHebrew(tz: string): string {
	const parts = tz.split('/')
	
	// Replace underscores with spaces in all parts
	const normalizedParts = parts.map(part => part.replace(/_/g, ' '))
	
	// Build Hebrew label
	const result: string[] = []
	
	// Translate continent/region
	if (normalizedParts.length >= 1) {
		const continent = HEBREW_TIMEZONE_TRANSLATIONS[normalizedParts[0]]
		if (continent) {
			result.push(continent)
		}
	}
	
	// Handle multi-part timezones (e.g., "America/Indiana/Indianapolis")
	if (normalizedParts.length >= 3) {
		// Translate middle part if it exists (e.g., "Indiana")
		const middle = HEBREW_TIMEZONE_TRANSLATIONS[normalizedParts[1]]
		if (middle) {
			result.push(middle)
		}
		// Translate last part (e.g., "Indianapolis")
		const city = HEBREW_TIMEZONE_TRANSLATIONS[normalizedParts[normalizedParts.length - 1]]
		if (city) {
			result.push(city)
		} else {
			// If no translation, use the original city name
			result.push(normalizedParts[normalizedParts.length - 1])
		}
	} else if (normalizedParts.length >= 2) {
		// Translate city/location
		const city = HEBREW_TIMEZONE_TRANSLATIONS[normalizedParts[1]]
		if (city) {
			result.push(city)
		} else {
			// If no translation, use the original city name
			result.push(normalizedParts[1])
		}
	}
	
	return result.length > 0 ? result.join(' / ') : tz
}

